name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir:
          - "1.11"
          - "1.3"
        otp:
          - "23"
          - "19"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install package dependencies
        run: mix deps.get

      - name: Check for valid formatting
        run: mix format --check-formatted

      - name: Run Credo static code analysis
        run: mix credo

      - name: Run unit tests
        run: mix test
