name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 1 */1 *"

jobs:
  test:
    name: Elixir ${{matrix.pair.elixir}} / OTP ${{matrix.pair.otp}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pair:
          - otp: "23"
            elixir: "1.10"
          - otp: "25"
            elixir: "main"

    env:
      MIX_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.pair.elixir }}
          otp-version: ${{ matrix.pair.otp }}

      - name: Restore deps cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-${{ hashFiles('**/mix.lock') }}-${{ github.sha }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-${{ hashFiles('**/mix.lock') }}
            deps-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}

      - name: Install package dependencies
        run: mix deps.get

      - name: Check for valid formatting
        run: mix format --check-formatted

      - name: Run unit tests
        run: mix test --color
